class PopulateLocations < ActiveRecord::Migration
  def change
    province = UserField.create(name: 'Province/State', field_type: 'dropdown', editable: true, description: 'Province/State', required: false, show_on_profile: true, position: 1)
    city     = UserField.create(name: 'City', field_type: 'dropdown', editable: true, description: 'City', required: false, show_on_profile: true, position: 2)
    UserField.create(name: 'Neighborhood', field_type: 'dropdown', editable: true, description: 'Neighborhood', required: false, show_on_profile: true, position: 3)

    british = UserFieldOption.create(user_field_id: province.id, value: 'British Columbia')

    UserFieldOption.create(user_field_id: city.id, value: '100 Mile House', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Abbotsford', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Alert Bay', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Anmore', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Armstrong', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Ashcroft', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Barriere', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Belcarra', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Bowen Island', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Burnaby', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Burns Lake', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Cache Creek', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Campbell River', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Canal Flats', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Castlegar', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Central Saanich', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Chase', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Chetwynd', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Chilliwack', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Clearwater', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Clinton', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Coldstream', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Colwood', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Comox', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Coquitlam', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Courtenay', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Cranbrook', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Creston', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Cumberland', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Dawson Creek', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Delta', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Duncan', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Elkford', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Enderby', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Esquimalt', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Fernie', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Fort St. James', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Fort St. John', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Fraser Lake', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Fruitvale', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Gibsons', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Gold River', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Golden', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Grand Forks', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Granisle', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Greenwood', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Harrison Hot Springs', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Hazelton', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Highlands', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Hope', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Houston', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Hudson', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Invermere', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Jumbo Glacier', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Kamloops', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Kaslo', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Kelowna', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Kent', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Keremeos', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Kimberley', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Kitimat', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Ladysmith', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Lake Country', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Lake Cowichan', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Langford', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Langley', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Lantzville', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Lillooet', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Lions Bay', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Logan Lake', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Lumby', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Lytton', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Mackenzie', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Maple Ridge', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Masset', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'McBride', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Merritt', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Metchosin', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Midway', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Mission', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Montrose', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Nakusp', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Nanaimo', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Nelson', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'New Denver', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'New Hazelton', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'New Westminster', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'North Cowichan', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'North Saanich', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'North Vancouver', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Northern Rockies', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Oak Bay', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Oliver', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Osoyoos', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Parksville', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Peachland', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Pemberton', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Penticton', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Pitt Meadows', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Port Alberni', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Port Alice', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Port Clements', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Port Coquitlam', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Port Edward', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Port Hardy', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Port McNeill', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Port Moody', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Pouce Coupe', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Powell River', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Prince George', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Prince Rupert', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Princeton', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Qualicum Beach', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Queen Charlotte', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Quesnel', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Radium Hot Springs', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Revelstoke', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Richmond', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Rossland', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Saanich', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Salmo', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Salmon Arm', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Sayward', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Sechelt', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Sicamous', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Sidney', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Silverton', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Slocan', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Smithers', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Sooke', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Spallumcheen', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Sparwood', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Squamish', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Stewart', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Summerland', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Sun Peaks', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Surrey', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Tahsis', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Taylor', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Telkwa', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Terrace', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Tofino', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Trail', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Tumbler Ridge', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Ucluelet', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Valemount', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Vancouver', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Vanderhoof', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Vernon', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Victoria', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'View Royal', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Warfield', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Wells', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'West Kelowna', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'West Vancouver', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Whistler', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'White Rock', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Williams Lake', parent_field_option_id: british.id)
    UserFieldOption.create(user_field_id: city.id, value: 'Zeballos', parent_field_option_id: british.id)
  end
end
